- name: Install packages to allow apt to use a repository over HTTPS
  apt: name={{item}} state=present
  with_items:
       - postgresql-client

- name: Create postgres networks
  docker_network:
    name: postgres

- name: Start postgres container.
  docker_container:
    name: postgres
    image: "{{docker_postgres_image | default('postgres:alpine') }}"
    state: started
    restart_policy: always
    networks:
      - name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env:
      POSTGRES_USER: "{{ postgres_admin_username }}"
      POSTGRES_PASSWORD: "{{ postgres_admin_password }}"
    ports:
      - '5432:5432'

- name: Install psycopg2
  pip:
    name: psycopg2-binary

