- name: update network interface
  template:
    src: netplan.yml.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: 0600
  register: netplan


- name: Apply netplan config
  command: netplan apply
  when: netplan.changed