---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    sha: v1.15.0
    hooks:
      - id: yamllint
        args:
          - >
            -d {
              extends: relaxed,
              rules: {
                line-length: { max: 120 }
              }
            }
          - "-s"
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.1.0a0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
