- name: Setup KVM hosts.
  hosts: kvm-hosts
  become: true
  vars_files:
    - vars/main.yml
    - vars/guests.yml
  roles:
    - role: /Users/ncrmro/code/ansible-galaxy/kvm-host
#  tasks:
##    - task: /Users/ncrmro/code/gitlab.com/jtco/ops/astrocyte/roles/gcp-jh/tasks/main.yml
#    - name: Run tasks/other.yaml instead of 'main'
#      include_role:
#        name: gcp-jh
#        tasks_from: init
