- name: Setup KVM hosts.ini.
  hosts: kvm-hosts.ini
  become: true
  vars_files:
    - vars/main.yml
  vars:
    - users:
        - name: ncrmro
          uid: 1000
          email_perfered: ncrmro@gmail.com
          update_password: on_create
          groups:
            - sudo
            - libvirt
            - libvirt-qemu
          generate_ssh_key: true
  roles:
    - role: ncrmro.kvm_host