- name: Setup KVM hosts.
  hosts: kvm-hosts
  become: true
  vars_files:
    - vars.yml
  vars:
    - users:
        - name: ncrmro
          uid: 1000
          email_perfered: ncrmro@gmail.com
          update_password: on_create
          groups:
            - sudo
            - libvirt
            - libvirt-qemu
          generate_ssh_key: true
  roles:
    #- kvm_host
    - kvm_guests