---
- name: Setup KVM hosts.
  hosts: kvm-hosts
  become: true
  vars_files:
    - vars/kvm.yml
    - vars/env.yml
    - vars/vault.yml
    - vars/users.yml
  roles:
    - kvm_host

- name: Setup KVM guests.
  hosts: kvm-hosts
  become: true
  vars_files:
    - vars/kvm.yml
    - vars/env.yml
    - vars/vault.yml
    - vars/users.yml
  roles:
    - kvm_guests