---
- name: Setup Docker hosts.
  hosts: docker-hosts
  become: true
  vars_files:
    - vars/kvm.yml
    - vars/env.yml
    - vars/vault.yml
    - vars/users.yml
  roles:
    - docker

- name: Set up dnode0 play
  hosts: dnode0
  become: true
  vars_files:
    - vars/kvm.yml
    - vars/env.yml
    - vars/vault.yml
    - vars/users.yml
  roles:
    - services/traefik
    - services/prometheus
    - services/postgres
    - services/grafana