---
- name: Update hosts add in security roles.
  hosts: baremetal
  become_user: root
  remote_user: ncrmro
  become: true
  vars_files:
    - vars/users.yml
    - vars/env.yml
  roles:
    - common
    - security
#TODO make work with router stuck on ubuntu 16
#    - users
#    - baremetal

- name: NAS hosts roles.
  hosts: nas
  become_user: root
  remote_user: ncrmro
  become: true
  vars_files:
    - vars/users.yml
    - vars/env.yml
  roles:
    - network_storage

- name: Setup KVM hosts.
  hosts: kvm-hosts
  become: true
  vars_files:
    - vars/kvm.yml
    - vars/env.yml
    - vars/vault.yml
    - vars/users.yml
  roles:
    - kvm_host

- name: Setup leviathian guests.
  hosts: leviathian
  become: true
  vars_files:
    - vars/kvm.yml
    - vars/env.yml
    - vars/vault.yml
    - vars/users.yml
  roles:
    - kvm_guests

- name: Secure newly provisioned guests.
  hosts: ubuntu
  become_user: root
  remote_user: ncrmro
  become: true
  vars_files:
    - vars/kvm.yml
    - vars/env.yml
    - vars/vault.yml
    - vars/users.yml
  roles:
    - common
    - security

- name: Setup Docker hosts.
  hosts: docker-hosts
  become: true
  vars_files:
    - vars/kvm.yml
    - vars/env.yml
    - vars/vault.yml
    - vars/users.yml
  roles:
    - docker