---
- name: Provision AWS infrastracture
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars/aws/general.yml
    - vars/aws/security_groups.yml
    - vars/vault.yml
    - vars/env.yml

#  vars:
#    ansible_ssh_private_key_file: "{{ ssh_key }}"
  roles:
    - aws/security
