---
- name: Setup Docker hosts.
  hosts: docker-hosts
  become: true
  vars_files:
    - vars/kvm.yml
    - vars/env.yml
    - vars/vault.yml
    - vars/users.yml
  roles:
    - docker

- name: Setup Docker services.
  hosts: dnode0
  become: true
  vars_files:
    - vars/kvm.yml
    - vars/env.yml
    - vars/vault.yml
    - vars/users.yml
#    vars:
    #prometheus_host_kvm: 192.168.1.71
  roles:
    - services/prometheus