---
- name: Provision AWS infrastracture
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars/aws/general.yml
    - vars/aws/security_groups.yml
    - vars/aws/ebs.yml
    - vars/aws/elastic_ip.yml
    - vars/env.yml
    - vars/vault/main.yml
    - vars/vault/aws.yml
  roles:
    - aws/elastic_ip
    - aws/security
    - aws/storage
    - aws/ec2

- name: Setup Routing
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars/aws/general.yml
    - vars/aws/security_groups.yml
    - vars/aws/ebs.yml
    - vars/aws/elastic_ip.yml
    - vars/env.yml
    - vars/vault/main.yml
    - vars/vault/routing.yml
    - vars/vault/aws.yml
  roles:
    - routing
