---
- name: "create disk: {{ kvm_vm_location}}/{{ guest.name }}.{{ guest.file_type }}"
  command: >
           qemu-img create
           -f {{ guest.file_type }}
           "{{ kvm_vm_location}}/{{ guest.name }}.{{ guest.file_type }}"
           "{{guest.disk_size}}"

- name: "Copy preseed preseed-ubuntu.cfg.j2"
  template:
    src: preseed-ubuntu.cfg.j2
    dest: "{{kvm_vm_location}}/preseed.cfg"
    owner: root
    group: root
    mode: 0600

- name: "create KVM guest {{ guest.name }}"
  command: >
            virt-install
            --name={{ guest.name }}
            --network=bridge=br0,model=virtio
            {{guest.initrd_inject}}
            {{guest.extra_args}}
            --location={{ guest.iso }}
            --ram={{ guest.memory }}
            --vcpus={{ guest.vcpus }}
            --cpu={{ guest.cpu | default("host") }}
            --disk={{ kvm_vm_location }}/{{ guest.name }}.{{ guest.file_type }}
            --graphics vnc
            --os-type={{ guest.os_type }}
            --os-variant={{ guest.os_variant }}
            --noreboot

- name: "Reboot: {{ guest.name }}"
  include_tasks: reboot.yml
  vars:
    name: "{{ guest.name }}"

- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: "{{ guest.domain }}"
    search_regex: OpenSSH
    delay: 10