astro_guests:
  - name: prometheus
    base_guest: "{{ kvm_base_guests_ubuntu18_04_server }}"
    hostname: prometheus
    domain: prometheus.local
    network_interface: br0

guests_k8:
  - name: k8node-razdsf
    memory: 2048
    base_guest: "{{ kvm_base_guests_ubuntu18_04_server }}"
    hostname: k8node_razdsf
    domain: k8node-razdsf.local
    network_interface: br0
  - name: k8node_apfvys
    memory: 2048
    base_guest: "{{ kvm_base_guests_ubuntu18_04_server }}"
    hostname: k8node_apfvys
    domain: k8node_apfvys.local
    network_interface: br0

#kvm_guests: "{{ astro_guests + guests_k8 }}"
kvm_guests: "{{ astro_guests }}"
