---
- name: List VMs
  virt: command=list_vms
  register: vms

- name: get VM disks
  command: ls "{{ kvm_vm_location }}"
  register: disks
  changed_when: "disks.rc != 0"

- name: Add base guest hosts
  add_host:
    hostname: "{{ item.name }}"
    groups:
      - kvm_guests
      - kvm_base_guests
    ansible_ssh_host: "{{ item.domain }}"
    ansible_user: "{{admin_username}}"
    ansible_ssh_private_key_file: "{{admin_ssh_key_path}}"
    ansible_python_interpreter: /usr/bin/python3
    #ansible_ssh_port: "{{ new_port }}"
  with_items: "{{ kvm_base_guests }}"

#- name: Add guest hosts
#  add_host:
#    hostname: "{{ item.name }}"
#    groups:
#      - kvm_guests
#    ansible_ssh_host: "{{ item.domain }}"
#    ansible_user: "{{admin_username}}"
#    ansible_ssh_private_key_file: "{{admin_ssh_key}}"
#    ansible_python_interpreter: /usr/bin/python3
#    #ansible_ssh_port: "{{ new_port }}"
#  with_items: "{{ kvm_guests }}"

# Example setting facts so that they will be persisted in the fact cache
- set_fact:
    vms: "{{vms}}"
    kvm_disks: "{{disks}}"
#    network_interfaces: "{{network_interfaces}}"
#    nets: "{{nets}}"
