- name: List VMs
  virt: command=list_vms
  register: vms

- name: "Clone guests {{ guest.name }} from base guests"
  include_tasks: util/clone.yml
  when: guest.name not in vms.list_vms

- name: "If guest {{ guest.name }} reach able by base_guest hostname {{ guest.base_guest.domain }}, lets shut it down."
  command: ping -c1 "{{ guest.base_guest.domain }}"
  register: ping_result
  when: guest.name not in vms.list_vms
  ignore_errors: yes

- name: "Ensure base_guest {{ guest.base_guest.name }} is shutdown before cloning guest { guest.name }}."
  import_tasks: util/shutdown.yml
  vars:
    name: "{{guest.base_guest.name}}"
  when: ping_result is success

- import_tasks: util/boot.yml
  vars:
      name: "{{guest.name}}"
  when: guest.name not in vms.list_vms

- name: "Wait 15 secods for {{ guest.name}} to be reachable at {{ guest.base_guest.domain }}"
  wait_for:
    host: "{{ guest.base_guest.domain }}"
    port: 22
    search_regex: OpenSSH
    timeout: 30
  when: guest.name not in vms.list_vms

- name: "Update cloned guests: {{ guest.name }} hostname"
  include_tasks: util/changehostname.yml
  when: guest.name not in vms.list_vms

- name: Wait for async change hostname..
  pause: seconds=45
  when: guest.name not in vms.list_vms

- import_tasks: util/reboot.yml
  vars:
    name: "{{ guest.name }}"
  when: guest.name not in vms.list_vms

- name: "Wait 30 secods for {{ guest.name }} to be reachable at {{ guest.domain }}"
  wait_for:
    host: "{{ guest.domain }}"
    port: 22
    search_regex: OpenSSH
    timeout: 30

#- name: Resize disk
#  include_tasks: util/resize_disk.yml
#  vars:
#    #original_size:
#    expanded_size: 40GB
