---

- import_tasks: gather_facts.yml

- name: Create base KVM guests
  include_tasks: base_guests.yml
  vars:
    guest: "{{ item }}"
  with_items: "{{ kvm_base_guests }}"

- name: Create guests
  include_tasks: guests.yml
  vars:
    guest: "{{ item }}"
  with_items: "{{ kvm_guests }}"
