netplan_network:
  version: 2
  ethernets:
    - name: enp3s0
      dhcp4: no
      dhcp6: no
    - name: enp4s0
      dhcp6: no
  bonds:
    - name: bond0
      dhcp4: yes
      dhcp6: yes
      interfaces:
        - enp3s0
        - enp4s0
      parameters:
        mode: 802.3ad
  bridges:
     - name: br0
       dhcp4: false
       dhcp6: false
       interfaces:
        - bond0
       optional: true
       addresses: [192.168.1.169/24]
       gateway4: 192.168.1.254
       nameservers:
         search: [.local]
         addresses: [192.168.1.100,192.168.1.254,9.9.9.9]

zfs_pools:
  ocean:
    devices:
      - ata-ST2000DM006-2DM164_Z4Z9Y1WS
      - ata-ST2000DM006-2DM164_Z4ZAQVXE
      - ata-ST2000DM006-2DM164_Z4ZAVGNM
      - ata-TOSHIBA_DT01ACA200_34AL79UGS
      - ata-WDC_WD20EARX-00PASB0_WD-WMAZA7977573
#    slog:
#      -





