netplan_network:
  network:
  version: 2
  ethernets:
    - name: enp0s25
      dhcp4: false
      dhcp6: false
  bridges:
    - name: br0
      dhcp4: false
      dhcp6: false
      interfaces:
       - enp0s25
      optional: true
      addresses: [192.168.1.69/24]
      gateway4: 192.168.1.254
      nameservers:
        search: [.local]
        addresses: [192.168.1.100,192.168.1.254,9.9.9.9,1.1.1.1]