---
- set_fact:
     ANSIBLE_HOST_KEY_CHECKING: False

- name: "add guest domain {{ guest.hostname}} and hostname {{ guest.domain }} to /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '127\.0\.1\.1[ \t]+\S+[ \t]+\S+'
    line: '127.0.1.1       {{ guest.domain }}        {{ guest.hostname }}'
    state: present
  delegate_to: "{{ guest.base_guest.hostname }}"
  connection: local

- name: "add hostname {{ guest.hostname }} to /etc/hostname"
  lineinfile:
    dest: /etc/hostname
    regexp: '^{{ guest.base_guest.hostname }}'
    line: '{{ guest.hostname }}'
    state: present
  async: 30
  poll: 0
  delegate_to: "{{ guest.base_guest.hostname }}"

- set_fact:
     ANSIBLE_HOST_KEY_CHECKING: True