hosts:
  wstat:
    name: ubuntu18_04_server
    mem: 4096
    cpus: 4
    os_type: linux
    os_variant: ubuntu16.04
    disk_size: 80G
    file_type: qcow2
    iso: http://us.archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/
    hostname: ubuntu18-04-server
    domain: ubuntu18-04-server.kvm
    initrd_inject: "--initrd-inject {{data_location}}/preseed.cfg"
    extra_args: '--extra-args="console-setup/ask_detect=false file=file:/preseed.cfg priority=critical quiet"'
  wstat:
    name: ubuntu18_04_server
    mem: 4096
    cpus: 4
    os_type: linux
    os_variant: ubuntu16.04
    disk_size: 80G
    file_type: qcow2
    iso: http://us.archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/
    hostname: ubuntu18-04-server
    domain: ubuntu18-04-server.kvm
    initrd_inject: "--initrd-inject {{data_location}}/preseed.cfg"
    extra_args: '--extra-args="console-setup/ask_detect=false file=file:/preseed.cfg priority=critical quiet"'