# TODO pass in single group id when needed
# https://github.com/atplanet/ansible-auto-scaling-tutorial/issues/6
#- name: ec2 module fails when providing named group if less than one is provided.
#  set_fact:
#     security_group:
#      - "{{ hostvars[inventory_hostname]['aws_sg_' + item.security_groups[0]].group_id }}"
#  cacheable: true
#  when: item.security_groups|length <= 1


- name: DEBUG ME
  debug:
    msg: "{{ item }}"

- name: Get the elastic ip name
  set_fact:
    os_drive_name: "{{item.name}}"

- debug:
    msg: "{{ os_drive_name }}"
#
#- debug:
#    msg: "{{ item.tags }}"
#
- name: allocate a new elastic IP without associating it to anything
  ec2_eip:
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    state: present
    region: "{{ ec2_region | default(aws_default_region) }}"
    public_ip: "{{ item.public_ip | default(false) }}"
    #private_ip_address: "{{ item.private_ip_address | default(false) }}"
    allow_reassociation: "{{ item.allow_reassociation | default(false) }}"
    release_on_disassociation: "{{ item.release_on_disassociation | default(false) }}"
  register: eip