
- name: Create networks
  docker_network:
    name: graylog_elasticsearch

- name: Start elasticsearch container.
  docker_container:
    name: graylog_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    #command: elasticsearch -Des.cluster.name="graylog"
    state: started
    restart_policy: always
    networks:
      - name: graylog_elasticsearch
    volumes:
      - graylog_elasticsearch_data:/usr/share/elasticsearch/data
    env:
      http.host: 0.0.0.0
      transport.host: localhost
      network.host: 0.0.0.0
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

# Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    mem_limit: 1g
#    ports:
#      - '127.0.0.1:27017:27017'

#sudo docker rm -f graylog mongo graylogelasticsearch ; sudo docker volume rm -f mongo_data graylog_config graylog_data graylog_plugins