
- name: Create networks
  docker_network:
    name: graylog_elasticsearch

- name: Start elasticsearch container.
  docker_container:
    name: graylog_elasticsearch
    image: "{{ docker_graylog_elasticsearch_image | default('docker.elastic.co/elasticsearch/elasticsearch:latest') }}"
    #command: elasticsearch -Des.cluster.name="graylog"
    state: started
    restart_policy: always
    networks:
      - name: graylog_elasticsearch
    volumes:
      - graylog_elasticsearch_data:/usr/share/elasticsearch/data
    env:
      cluster.name: graylog
      http.host: 0.0.0.0
      network.host: 0.0.0.0
      transport.host: localhost
      bootstrap.memory_lock: true
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"

# Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    mem_limit: 1g
#    ports:
#      - '127.0.0.1:27017:27017'

# sudo docker rm -f graylog_elasticsearch && sudo docker volume rm graylog_elasticsearch_data
