- import_tasks: mongo.yml
- import_tasks: elastic_search.yml

- name: Create graylog volumes
  docker_volume:
    name: "{{ item }}"
  with_items:
    - graylog_config
    - graylog_data
    - graylog_plugins

- name: Copy graylog configuration file.
  template:
    src: graylog.conf.j2
    dest: /var/lib/docker/volumes/graylog_config/_data/graylog.conf
    mode: 0600

- import_tasks: elastic_search.yml