
- name: Ensure group Provisioner groups exists
  group:
    name: "{{item}}"
    state: present
  with_items:
    - provisioner

- name: Allow 'provisioner' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%provisioner'
    line: '%provisioner ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add the users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
    generate_ssh_key: "{{ item.generate_ssh_key }}"
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519.pub
    update_password: "{{ item.update_password }}"
  with_items: "{{ users }}"

- name: Add Ansible Provisioner
  user:
    name: "{{item.name}}"
    groups: "{{item.groups}}"
    generate_ssh_key: "{{item.generate_ssh_key | default(false) }}"
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519.pub
  with_items: "{{provisioners}}"


- name: Upload admin user ssh keys to provisioner accounts.
  authorized_key:
    user: "{{item.name}}"
    key: "{{ ssh_public_key }}"
  with_items: "{{provisioners}}"