---
- name: Update hosts add in security roles.
  hosts: baremetal
  become_user: root
  remote_user: ncrmro
  become: true
  vars_files:
    - vars/users.yml
    - vars/env.yml
  roles:
    - common
    - security
    - users
    - baremetal

- name: NAS hosts roles.
  hosts: nas
  become_user: root
  remote_user: ncrmro
  become: true
  vars_files:
    - vars/users.yml
    - vars/env.yml
  roles:
    - network_storage

- name: Setup KVM hosts.
  hosts: kvm-hosts
  become: true
  vars_files:
    - vars/kvm.yml
    - vars/env.yml
    - vars/users.yml
    - vars/vault/main.yml
  roles:
    - kvm_host