- name: Copy Service Account
  template:
    src: admin/cluster_role_binding.yaml.j2
    #dest: "{{ ansible_env.HOME }}/role-deployment-manager.yml"
    dest: "/home/ubuntu/cluster_role_binding.yaml"
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: Create Service Account
  #shell: kubectl create -f "{{ansible_env.HOME}}/role-deployment-manager.yml"
  shell: kubectl create -f /home/ubuntu/cluster_role_binding.yaml
  become: false

- name: Copy ClusterRoleBinding
  template:
    src: admin/service_account.yaml.j2
    #dest: "{{ ansible_env.HOME }}/role-deployment-manager.yml"
    dest: "/home/ubuntu/service_account.yaml"
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: Create ClusterRoleBinding
  #shell: kubectl create -f "{{ansible_env.HOME}}/role-deployment-manager.yml"
  shell: kubectl create -f /home/ubuntu/service_account.yaml
  become: false

- set_fact:
    k8_config_path: /etc/kubernetes
    k8_certs_path: /etc/kubernetes/pki/
    k8_user_certs_path: /home/ubuntu/certs/

- set_fact:
    k8_ca_private_key: "{{k8_certs_path}}ca.key"
    k8_ca_certificate: "{{k8_certs_path}}ca.crt"
    k8_user_private_key: "{{k8_user_certs_path }}ubuntu.key"
    k8_user_certificate: "{{k8_user_certs_path }}ubuntu.crt"
    k8_user_csr: "{{k8_user_certs_path }}ubuntu.csr"

- name: Copy cluster certificate to local machine
  fetch:
    src: "{{ k8_ca_certificate }}"
    dest: "~/.kube/certs/ca.crt"
    flat: true
  become: false

- name: Copy user key to local machine
  fetch:
    src: "{{ k8_user_private_key }}"
    dest: "~/.kube/certs/ubuntu.pem"
    flat: true
  become: false

- name: Copy user certificate to local machine
  fetch:
    src: "{{ k8_user_certificate}}"
    dest: "~/.kube/certs/ubuntu.cert"
    flat: true
  become: false