# create a test.my.com A record to point to 127.0.0.1

- cloudflare_dns:
    zone: "{{cf_zone.zone}}"
    record: "{{ item.record + '.' + cf_zone.zone }}"
    type: "{{item.type}}"
    value: "{{item.value}}"
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_api_key }}"
    solo: "{{ item.solo | default(true) }}"
    ttl: "{{ item.TTL | default(3600) }}"
    proxied: "{{item.proxied | default(fault) }}"
  when: item.record is defined
  with_items: "{{ cf_zone.types }}"

- cloudflare_dns:
    zone: "{{cf_zone.zone}}"
    type: "{{item.type}}"
    value: "{{item.value}}"
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_api_key }}"
    solo: "{{ item.solo | default(true) }}"
    ttl: "{{ item.TTL | default(3600) }}"
    proxied: "{{item.proxied | default(fault) }}"
  when: item.record is not defined
  with_items: "{{ cf_zone.types }}"

# https://docs.ansible.com/ansible/2.5/modules/cloudflare_dns_module.html