---
# https://github.com/stuvusIT/zfs-storage/blob/master/tasks/install_nfs.yml
- name: Install packages to allow apt to use a repository over HTTPS
  apt: name={{item}} state=present
  with_items:
       - nfs-kernel-server

- name: Enable and start NFS server
  service:
    name: nfs-kernel-server.service
    state: started
    enabled: True
  when: ansible_pkg_mgr == "apt"

- name: Create NFS exports.d directory
  file:
    path: /etc/exports.d/
    state: directory