- name: Create unifi networks
  docker_network:
    name: unifi

- name: Start unifi container.
  docker_container:
    name: unifi
    image: "{{ docker_unifi_image | default('linuxserver/unifi:latest') }}"
    state: started
    restart_policy: always
    networks:
      - name: unifi
    volumes:
      - unifi_data:/config
#    env:
#      unifi_INITDB_ROOT_USERNAME: "{{ unifi_admin_username }}"
#      unifi_INITDB_ROOT_PASSWORD: "{{ unifi_admin_password }}"
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789