---

- name: Creates directory
  file:
    path: /etc/prometheus
    state: directory
    owner: root
    group: root


- name: Creates directory
  file:
    path: /var/lib/prometheus
    state: directory
    owner: root
    group: root

- name: Check prometheus node exporter exists.
  stat:
    path: "/usr/local/bin/node_exporter"
  register: node_exporter

- name: Download and unarchive prometheus node exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v0.15.1/node_exporter-0.15.1.linux-amd64.tar.gz
    dest: /tmp
    creates: /usr/node_exporter-0.15.1.linux-amd64/node_exporter
    remote_src: yes
  when: node_exporter.stat.exists != true

- name: Extract Exporter
  shell: >
    cp /tmp/node_exporter-0.15.1.linux-amd64/node_exporter /usr/local/bin
  when: node_exporter.stat.exists != true

- name: Copy Exporter configuration file.
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0600

- name: enable service httpd and ensure it is not masked
  systemd:
    name: node_exporter
    state: restarted
    enabled: yes

- name: Allow from Prometheus Host
  ufw:
    rule: allow
    port: 9100
    src: '{{ common_node_exporter_ip }}'
  when: common_node_exporter_ip is defined

- name: Secure instance
  ufw:
    state: reloaded