- name: Start prometheus container.
  docker_container:
    name: prometheus
    image: "{{ docker_prometheus_image | default('prom/prometheus') }}"
    hostname: prometheus.jtronics.co
    state: started
    recreate: true
    user: 0
    restart_policy: always
    published_ports:
      - '127.0.0.1:9090:9090'
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/data
    networks:
      - name: traefik
      - name: postgres
      - name: prometheus
    etc_hosts:
      leviathian.local: "{{ kvm_guest_leviathian }}"
      earthdiver.local: "{{ kvm_guest_earthdiver }}"
    volumes:
      - prometheus_config:/etc/prometheus/
      - prometheus_data:/data
    labels:
     traefik.enable: "true"
     traefik.frontend.rule: "Host:prometheus.jtronics.co"
     traefik.port: "9090"
     traefik.docker.network: traefik
