---
- name: Creates VM directory
  file:
    path: "{{kvm_vm_location}}"
    state: directory
    owner: libvirt-qemu
    group: libvirt-qemu
    recurse: true

- name: Packages needed by ansible
  apt: name={{ packages }} state=present
  vars:
    packages:
         - pkg-config
         - python-pip
         - python3-lxml

- name: Install kvm and tools
  apt: name={{ packages }} state=present
  vars:
    packages:
         - qemu-kvm
         - libvirt-bin
         - libvirt-dev
         - virtinst
         - libguestfs-tools


- name: start libvirtd
  service: name=libvirtd state=started enabled=yes
  register: libvirtd

- name: wait for libvirtd to get up
  pause: seconds=30
  when: libvirtd.changed

- name: Install libvirt-python
  pip:
    name: libvirt-python
    version: 4.0.0

- name: Enanable Iommu
  lineinfile:
    dest: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="intel_iommu=on"'
    state: present
  notify: update grub

- include_tasks: arm.yml